### PR TITLE
Disabled default replacement of links

### PR DESCRIPTION
**Pull request by erisanolasheni**
Disabled automatic replacements of links, which causing issues.

### CODE REVIEW

**Comment by erisanolasheni** [comment]
**Issue:** **django-precise-bbcode** automatically replaces URL in content, this should not be. Not all URLs would want to be replaced.

**Comment by ellmetha** [comment]
This PR is breaking all the tests, and the change of behaviour is not backward-compatible. Since it's a very old PR I will close it for now, and we will address this as part of the related issue you created. 🙂

**Comment by theinvestigamer** [comment]
> This PR is breaking all the tests, and the change of behaviour is not backward-compatible. Since it's a very old PR I will close it for now, and we will address this as part of the related issue you created. 🙂

This issue remains unsolved, there should be a parser setting for not replacing URL's by default. I have all built ins disabled, none of my tags replace urls, yet they are still being replaced somehow sadly

**Comment by erisanolasheni** [comment]
We will make PRs and expect a merge, if non, we create another version of
this to be maintained.

**Pull request closed without merging**
